theme = "snazzy"

[editor]
line-number = "relative"
bufferline = "multiple"
cursorline = true
default-line-ending = "lf"

[editor.cursor-shape]
insert = "bar"
select = "underline"

[editor.indent-guides]
render = true

[editor.whitespace.render]
tab = "all"

[editor.whitespace.charaters]
tab = "→"
tabpad = "·"

[keys.normal]
# 1. shift right to home row
h = "collapse_selection"
A-h = "flip_selections"
j = "move_char_left"
k = "move_line_down"
l = "move_line_up"
";" = "move_char_right"

# 2. add jump left and right
A-j = "move_prev_word_start"
"A-;" = "move_next_word_end"

# 3. switch C-b to C-v for tmux
"C-b" = "no_op"
"C-v" = "page_up"

# see 1., 2., and 3.
[keys.select]
h = "collapse_selection"
A-h = "flip_selections"
j = "extend_char_left"
k = "extend_line_down"
l = "extend_line_up"
";" = "extend_char_right"
A-j = "extend_prev_word_start"
"A-;" = "extend_next_word_end"
C-b = "no_op"
C-v = "page_up"

# 4. disable movement in insert mode
[keys.insert]
up = "no_op"
down = "no_op"
left = "no_op"
right = "no_op"
pageup = "no_op"
pagedown = "no_op"
home = "no_op"
end = "no_op"

# see 1.
[keys.normal.g]
h = "no_op"
j = "goto_line_start"
k = "move_line_down"
l = "move_line_up"
";" = "goto_line_end"

[keys.select.g]
h = "no_op"
j = "goto_line_start"
k = "extend_line_down"
l = "extend_line_up"
";" = "goto_line_end"

# see 1. and 3.
[keys.normal.z]
j = "no_op"
k = "scroll_down"
l = "scroll_up"
C-b = "no_op"
C-v = "page_up"

[keys.normal.Z]
j = "no_op"
k = "scroll_down"
l = "scroll_up"
C-b = "no_op"
C-v = "page_up"

[keys.select.z]
j = "no_op"
k = "scroll_down"
l = "scroll_up"
C-b = "no_op"
C-v = "page_up"

[keys.select.Z]
j = "no_op"
k = "scroll_down"
l = "scroll_up"
C-b = "no_op"
C-v = "page_up"

# see 1.
[keys.normal.C-w]
h = "no_op"
j = "jump_view_left"
k = "jump_view_down"
l = "jump_view_up"
";" = "jump_view_right"
C-h = "no_op"
C-j = "jump_view_left"
C-k = "jump_view_down"
C-l = "jump_view_up"
"C-;" = "jump_view_right"
H = "no_op"
J = "swap_view_left"
K = "swap_view_down"
L = "swap_view_up"
":" = "swap_view_right"

[keys.select.C-w]
h = "no_op"
j = "jump_view_left"
k = "jump_view_down"
l = "jump_view_up"
";" = "jump_view_right"
C-h = "no_op"
C-j = "jump_view_left"
C-k = "jump_view_down"
C-l = "jump_view_up"
"C-;" = "jump_view_right"
H = "no_op"
J = "swap_view_left"
K = "swap_view_down"
L = "swap_view_up"
":" = "swap_view_right"

[keys.normal.space.w]
h = "no_op"
j = "jump_view_left"
k = "jump_view_down"
l = "jump_view_up"
";" = "jump_view_right"
C-h = "no_op"
C-j = "jump_view_left"
C-k = "jump_view_down"
C-l = "jump_view_up"
"C-;" = "jump_view_right"
H = "no_op"
J = "swap_view_left"
K = "swap_view_down"
L = "swap_view_up"
":" = "swap_view_right"

[keys.select.space.w]
h = "no_op"
j = "jump_view_left"
k = "jump_view_down"
l = "jump_view_up"
";" = "jump_view_right"
C-h = "no_op"
C-j = "jump_view_left"
C-k = "jump_view_down"
C-l = "jump_view_up"
"C-;" = "jump_view_right"
H = "no_op"
J = "swap_view_left"
K = "swap_view_down"
L = "swap_view_up"
":" = "swap_view_right"
