theme = "snazzy"

[editor]
line-number = "relative"
bufferline = "multiple"
cursorline = true
default-line-ending = "lf"

[editor.cursor-shape]
insert = "bar"
select = "underline"

[editor.indent-guides]
render = true

[editor.whitespace.render]
tab = "all"

[editor.whitespace.charaters]
tab = "→"
tabpad = "·"

# 1. use colemak layout and shift right to home row
# using `l` for newline, `y` for insert, and `j` for yank.
[keys.normal]
h = "collapse_selection"
"A-h" = "flip_selections"
n = "move_char_left"
"A-n" = "move_prev_word_start"
e = "move_line_down"
i = "move_line_up"
o = "move_char_right"
"A-o" = "move_next_word_end"
"C-b" = "no_op"
"C-v" = "page_up"
y = "insert_mode"
Y = "insert_at_line_start"
l = "open_below"
L = "open_above"
j = "yank"
J = "no_op"
k = "no_op"

# see 1.
[keys.select]
h = "collapse_selection"
"A-h" = "flip_selections"
n = "extend_char_left"
e = "extend_line_down"
i = "extend_line_up"
o = "extend_char_right"
"A-o" = "extend_next_word_end"
"A-n" = "extend_prev_word_start"
"C-b" = "no_op"
"C-v" = "page_up"
y = "insert_mode"
Y = "insert_at_line_start"
l = "open_below"
L = "open_above"
j = "yank"
J = "no_op"
k = "no_op"

# no newbie keys
[keys.insert]
up = "no_op"
down = "no_op"
left = "no_op"
right = "no_op"
pageup = "no_op"
pagedown = "no_op"
home = "no_op"
end = "no_op"

# see 1.
[keys.normal.g]
h = "no_op"
j = "no_op"
k = "no_op"
l = "no_op"
n = "goto_line_start"
e = "move_line_down"
i = "move_line_up"
o = "goto_line_end"

# see 1.
[keys.select.g]
h = "no_op"
j = "no_op"
k = "no_op"
l = "no_op"
n = "goto_line_start"
e = "move_line_down"
i = "move_line_up"
o = "goto_line_end"

# see 1.
[keys.normal.z]
e = "scroll_down"
i = "scroll_up"
j = "no_op"
k = "no_op"

# see 1.
[keys.normal.Z]
e = "scroll_down"
i = "scroll_up"
j = "no_op"
k = "no_op"

# see 1.
[keys.select.z]
e = "scroll_down"
i = "scroll_up"
j = "no_op"
k = "no_op"

# see 1.
[keys.select.Z]
e = "scroll_down"
i = "scroll_up"
j = "no_op"
k = "no_op"

# see 1.
[keys.normal.space]
j = "yank_to_clipboard"
J = "yank_main_selection_to_clipboard"

# see 1.
[keys.select.space]
j = "yank_to_clipboard"
J = "yank_main_selection_to_clipboard"

# see 1.
[keys.normal."C-w"]
n = "jump_view_left"
e = "jump_view_down"
i = "jump_view_up"
o = "jump_view_right"
"C-n" = "jump_view_left"
"C-e" = "jump_view_down"
"C-i" = "jump_view_up"
"C-o" = "jump_view_right"
N = "swap_view_left"
E = "swap_view_down"
I = "swap_view_up"
O = "swap_view_right"
h = "no_op"
j = "no_op"
k = "no_op"
l = "no_op"
H = "no_op"
J = "no_op"
K = "no_op"
L = "no_op"
"C-h" = "no_op"
"C-j" = "no_op"
"C-k" = "no_op"
"C-l" = "no_op"

# see 1.
[keys.select."C-w"]
n = "jump_view_left"
e = "jump_view_down"
i = "jump_view_up"
o = "jump_view_right"
"C-n" = "jump_view_left"
"C-e" = "jump_view_down"
"C-i" = "jump_view_up"
"C-o" = "jump_view_right"
N = "swap_view_left"
E = "swap_view_down"
I = "swap_view_up"
O = "swap_view_right"
h = "no_op"
j = "no_op"
k = "no_op"
l = "no_op"
H = "no_op"
J = "no_op"
K = "no_op"
L = "no_op"
"C-h" = "no_op"
"C-j" = "no_op"
"C-k" = "no_op"
"C-l" = "no_op"

# see 1.
[keys.normal.space.w]
n = "jump_view_left"
e = "jump_view_down"
i = "jump_view_up"
o = "jump_view_right"
"C-n" = "jump_view_left"
"C-e" = "jump_view_down"
"C-i" = "jump_view_up"
"C-o" = "jump_view_right"
N = "swap_view_left"
E = "swap_view_down"
I = "swap_view_up"
O = "swap_view_right"
h = "no_op"
j = "no_op"
k = "no_op"
l = "no_op"
H = "no_op"
J = "no_op"
K = "no_op"
L = "no_op"
"C-h" = "no_op"
"C-j" = "no_op"
"C-k" = "no_op"
"C-l" = "no_op"

# see 1.
[keys.select.space.w]
n = "jump_view_left"
e = "jump_view_down"
i = "jump_view_up"
o = "jump_view_right"
"C-n" = "jump_view_left"
"C-e" = "jump_view_down"
"C-i" = "jump_view_up"
"C-o" = "jump_view_right"
N = "swap_view_left"
E = "swap_view_down"
I = "swap_view_up"
O = "swap_view_right"
h = "no_op"
j = "no_op"
k = "no_op"
l = "no_op"
H = "no_op"
J = "no_op"
K = "no_op"
L = "no_op"
"C-h" = "no_op"
"C-j" = "no_op"
"C-k" = "no_op"
"C-l" = "no_op"
