theme = "snazzy"

[editor]
line-number = "relative"
bufferline = "multiple"
cursorline = true

[editor.cursor-shape]
insert = "bar"
select = "underline"

[editor.indent-guides]
render = true

[editor.whitespace.render]
tab = "all"

[editor.whitespace.charaters]
tab = "→"
tabpad = "·"

[keys.normal]
h = "collapse_selection"
"A-h" = "flip_selections"
j = "move_char_left"
A-j = "move_prev_word_start"
k = "move_line_down"
l = "move_line_up"
";" = "move_char_right"
"A-;" = "move_next_word_end"

[keys.select]
h = "collapse_selection"
"A-h" = "flip_selections"
j = "extend_char_left"
k = "extend_line_down"
l = "extend_line_up"
";" = "extend_char_right"
"A-;" = "extend_next_word_end"
A-j = "extend_prev_word_start"

[keys.insert]
up = "no_op"
down = "no_op"
left = "no_op"
right = "no_op"
pageup = "no_op"
pagedown = "no_op"
home = "no_op"
end = "no_op"

[keys.normal.g]
h = "no_op"
j = "goto_line_start"
k = "move_line_down"
l = "move_line_up"
";" = "goto_line_end"

[keys.select.g]
h = "no_op"
j = "goto_line_start"
k = "extend_line_down"
l = "extend_line_up"
";" = "goto_line_end"

[keys.normal.z]
j = "no_op"
k = "scroll_down"
l = "scroll_up"

[keys.normal.Z]
j = "no_op"
k = "scroll_down"
l = "scroll_up"

[keys.select.z]
j = "no_op"
k = "scroll_down"
l = "scroll_up"

[keys.select.Z]
j = "no_op"
k = "scroll_down"
l = "scroll_up"

[keys.normal."C-w"]
h = "no_op"
j = "jump_view_left"
k = "jump_view_down"
l = "jump_view_up"
';' = "jump_view_right"
'C-h' = "no_op"
'C-j' = "jump_view_left"
'C-k' = "jump_view_down"
'C-l' = "jump_view_up"
'C-;' = "jump_view_right"

[keys.select."C-w"]
h = "no_op"
j = "jump_view_left"
k = "jump_view_down"
l = "jump_view_up"
';' = "jump_view_right"
'C-h' = "no_op"
'C-j' = "jump_view_left"
'C-k' = "jump_view_down"
'C-l' = "jump_view_up"
'C-;' = "jump_view_right"
